### ISSUE TITLE
runtime error - huber_w division by zero

### ISSUE THREAD

**Issue by jasonebox** [jasonebox/SICE_classes2#1]
for one date, 2017-07-12, I am getting for huber_w a runtime error, ZeroDivisionError: division by zero

see 
https://github.com/jasonebox/SICE_classes2/blob/cd0052aa763f2306d72ea6bb0108cf1853065581/src/SICE_classes_SVC_v2.py#L467
https://github.com/jasonebox/SICE_classes2/blob/cd0052aa763f2306d72ea6bb0108cf1853065581/src/SICE_classes_SVC_v2.py#L468

**Comment by wehrad** [comment]
There are 0s in `w` or `sigma`, either remove them or set them to a very low value?
