### ISSUE TITLE
shapefile issue

### ISSUE THREAD

**Issue by jasonebox** [jasonebox/SICE_classes2#2]
I get an error I have gotten around by re-drawing lables. But I just spent a lot of time labeling one label that I don't want to re-label

I think the error below may be get-aroundable!

**TypeError: argument of type 'NoneType' is not iterable**

https://github.com/jasonebox/SICE_classes2/blob/cd0052aa763f2306d72ea6bb0108cf1853065581/src/SICE_classes_SVC_v2.py#L374

**Comment by wehrad** [comment]
what do the variables `temp` and `ROI_label` contain in your run, right before the error?

**Comment by wehrad** [comment]
Looks like either the file behind ROI or temp might be empty/inexistant
